services:

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "8000:8000"
    platform: linux/amd64
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis(host='redis').ping()"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./services/orchestrator:/app
      - ./shared:/app/shared
      
  watchdog:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile

    command: python watchdog_runner.py

    depends_on:
      - redis

    environment:
      - REDIS_HOST=redis

    volumes:
      - ./services/orchestrator:/app
      - ./shared:/app/shared
