import os
import subprocess
import time
import httpx
import pytest

PATHWAY_URL = "http://localhost:8080/"

def test_pathway_stream_ingestion():
    # Determine the python path to execute poc/pathway_stream.py
    # We check if we can run it with the parent venv python or the default python
    python_exe = "python"
    venv_python = os.path.join("..", "venv", "Scripts", "python.exe")
    if os.path.exists(venv_python):
        python_exe = venv_python

    cmd = [python_exe, "poc/pathway_stream.py"]
    
    # 1. Clean up old output files
    if os.path.exists("events.txt"):
        try:
            os.remove("events.txt")
        except Exception:
            pass

    # 2. Start the Pathway stream in the background
    try:
        process = subprocess.Popen(cmd)
    except OSError as e:
        # If the virtual environment python is not executable (e.g. cloud provider not running),
        # fall back to the global system python interpreter
        print(f"Warning: Failed to execute virtual environment python ({e}). Falling back to global python...")
        cmd = ["python", "poc/pathway_stream.py"]
        process = subprocess.Popen(cmd)
    
    try:
        # Allow Pathway to initialize and start the server
        time.sleep(3.0)
        
        # 3. Send a test POST request to the Pathway REST connector
        payload = {
            "task_id": "test-stream-id-999",
            "event_type": "TEST_RUN",
            "payload": "Pathway stream integration test success!",
            "timestamp": time.time()
        }
        
        response = httpx.post(PATHWAY_URL, json=payload, timeout=5.0)
        assert response.status_code == 200, f"Expected 200 OK, got {response.status_code}"
        
        # 4. Wait for Pathway to process the micro-batch and write to CSV
        time.sleep(3.0)
        
        # 5. Verify that the output CSV exists and contains the ingested data
        assert os.path.exists("events.txt"), "events.txt was not generated by Pathway."
        
        with open("events.txt", "r") as f:
            content = f.read()
            assert "test-stream-id-999" in content, "Ingested task_id not found in CSV."
            assert "Pathway stream integration test success!" in content, "Ingested payload not found in CSV."
            
        print("\nPathway Stream Test Passed!")

    finally:
        # 6. Clean up: terminate the background Pathway stream
        process.terminate()
        process.wait()

if __name__ == "__main__":
    test_pathway_stream_ingestion()
